// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import TodoFormController from "./todo_form_controller";
application.register("todo-form", TodoFormController);

import TaskSearchAutocompleteController from "./task_search_autocomplete_controller";
application.register(
  "task-search-autocomplete",
  TaskSearchAutocompleteController
);
